"LR": 0.0005
"NUM_ENVS": 256
"NUM_STEPS": 500
"TOTAL_TIMESTEPS": 1e7
"UPDATE_EPOCHS": 2
"NUM_MINIBATCHES": 500
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"CLIP_EPS": 0.2
"ENT_COEF": 0.01
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.5
"ACTIVATION": "relu"
"ENV_NAME": "territory_open"
"REW_SHAPING_HORIZON": 5e6 # for how many timesteps add a shaping reward
"SHAPING_BEGIN": 1e6
"ENV_KWARGS": 
  "num_agents" : 9
  "num_inner_steps" : 1000
  "shared_rewards" : False
  "cnn" : True
  "jit" : True
  

"ANNEAL_LR": True
"SEED": 30
"NUM_SEEDS": 1
"TUNE": False

"REWARD": "individual" # individual; common
"GIF_NUM_FRAMES": 250

# WandB Params
"ENTITY": ""
"PROJECT": "socialjax"
"WANDB_MODE" : "online"
"WANDB_TAGS":
  - INDIVIDUAL_REWARD # COMMON_REWARD